spring:
    profiles:
        active:
        - dev
---
#开发环境
spring:
    profiles: dev   
    application:
        name:microservicecloud-config-lzz-dev
---
 #测试环境
spring:
    profiles:test   
    application:
        name:microservicecloud-config-lzz-test
   
#一定要保存utf-8格式
        
